---
all:
  children:
    vpn:
      hosts:
        #        wgd-de: {}
        x-kz: {}
    web:
      hosts:
        sts-ru: {}
    docker:
      children:
        web: {}
    xray:
      hosts:
        x-kz: {}
